### ISSUE TITLE
Issues in spacetorch

### ISSUE THREAD

**Issue by YunhaoLi12138** [neuroailab/TDANN#4]
Hi, I am trying to replicate the result of the paper by training a model from the begining. I have installed all dependencies properly.
The configuration file I use is: 
```
# @package _global_
config:
  CHECKPOINT:
    DIR: "/data/out/simclr_spatial_SG_pretrain_minimal_aug_biased"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 100 # in units of epochs
  DATA:
    NUM_DATALOADER_WORKERS: 8
    TRAIN:
      DATA_SOURCES: [/data]
      DATASET_NAMES: imagenet1k_folder # this is a lie but I don't think it matters
      DATA_PATHS: ["/data/64qv3/osfstorage/tdann_data/datasets/sine_grating_images_ori_bias"]
      BATCHSIZE_PER_REPLICA: 128
      LABEL_TYPE: sample_index 
      TRANSFORMS:
        - name: ImgReplicatePil
          num_times: 2
        - name: RandomResizedCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      COLLATE_FUNCTION: simclr_collator
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      DATA_LIMIT: -1
      DROP_LAST: True
  MODEL:
    TRUNK:
      NAME: spatial_resnet18
      TRUNK_PARAMS:
        position_dir: "/data/64qv3/osfstorage/tdann_data/tdann/positions/supervised_resnet18_lw0/resnet18_retinotopic_init_fuzzy_swappedon_SineGrating2019"
    HEAD:
      PARAMS: [
        [
          ["mlp", {"dims": [512, 512], "use_relu": True}],
          ["mlp", {"dims": [512, 128]}]
        ],
        ["identity", {}]
      ]
    SYNC_BN_CONFIG:
        CONVERT_BN_TO_SYNC_BN: True
        SYNC_BN_TYPE: pytorch
  LOSS:
    name: spatial_correlation_simclr_info_nce_loss
    spatial_correlation_simclr_info_nce_loss:
      temperature: 0.1
      buffer_params:
        embedding_dim: 128
      neighborhoods_per_batch: 1
      layer_weights:
        layer1_0: 2.5
        layer1_1: 2.5
        layer2_0: 2.5
        layer2_1: 2.5
        layer3_0: 2.5
        layer3_1: 2.5
        layer4_0: 2.5
        layer4_1: 2.5
  OPTIMIZER:
    name: sgd
    use_larc: False
    weight_decay: 0.000001
    momentum: 0.9
    nesterov: False
    num_epochs: 2000 
    regularize_bn: False
    regularize_bias: True
    param_schedulers:
      lr:
        auto_lr_scaling:
          auto_scale: true
          base_value: 0.3
          base_lr_batch_size: 256
        name: cosine
        start_value: 0.15   # LR for batch size 256
        end_value: 0.0000
        update_interval: step
  METERS:
    name: ""
  TRAINER:
    TRAIN_STEP_NAME: custom_train_step
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 1 # 1 GPU
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  VERBOSE: True
  LOG_FREQUENCY: 500
  TEST_ONLY: False
  TEST_MODEL: False
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  TENSORBOARD_SETUP:
    USE_TENSORBOARD: true
```
I encountered several issues:
1) in train.py, ``` from spacetorch.utils import use_gpus ``` failed to import use_gpus, I need to change it to ```from spacetorch.utils.gpu_utils import use_gpus``` 
2) In "/TDANN/spacetorch/datasets/retinal_waves.py", ```from spacetorch.paths import RWAVE_CONTAINER_PATH``` failed and ```RWAVE_CONTAINER_PATH``` is not defined in spacetorch/paths.py .
3) cannot import name 'RetinalWaveData' and 'DEFAULT_RWAVE_DIRS' ```from .retinal_waves import RetinalWaveData, DEFAULT_RWAVE_DIRS```.
4) In 'spacetorch/utils/vissl/registration.py' These imports failed and I don't see them define anywhere in the repo:
```
from spacetorch.models.trunks.resnet_locally_connected import *  # noqa
from spacetorch.models.trunks.tiny_lc import *  # noqa
from spacetorch.models.trunks.stegosaurus import *
from spacetorch.train_steps.custom_train_step import *  # noqa
from spacetorch.train_steps.stego_train_step import *  # noqa
from spacetorch.train_steps.nonspatial_stego_train_step import *  # noqa
```
Is it an environment issue? Or is there something wrong with my configuration file? Thank you so much!
